#goal definition
geometry_msgs/PoseStamped[] goals
int8 targetId
string taskType
int8 taskId
int8 robotId
---
#result definition
bool isCompleted
int8 taskId
int8 robotId
---
#feedback
int8 robotId
int8 doorId 
time measureTime
uint8 doorStatus
